# Generated by Django 5.2.8 on 2026-07-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_product_fields_recipe_meta'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localrecipe',
            options={'verbose_name': 'Локальный рецепт', 'verbose_name_plural': 'Локальные рецепты'},
        ),
        migrations.AlterField(
            model_name='localrecipe',
            name='instructions',
            field=models.TextField(verbose_name='Инструкции'),
        ),
        migrations.AlterField(
            model_name='localrecipe',
            name='prep_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Время (мин)'),
        ),
        migrations.AlterField(
            model_name='localrecipe',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Название'),
        ),
    ]
